export const PLAYERS_ID = {
  USER: 'user',
  MACHINE: 'machine',
}

export const BOARD_SETTINGS = {
  COLUMNS: 7,
  SPOT_MARGIN_X: 3.5,
  SPOT_MARGIN_Y: 3,
  SPOT_RADIUS: 87 / 2,
  SPOT_BORDER_WIDTH: 2,
  SPOTS_PER_COLUMN: 6,
  CANVAS_WIDTH: 659,
  CANVAS_HEIGHT: 564,
}

export const SPOT_STATUSES = {
  DEFAULT: 'default',
  PRE_SELECTED: 'pre-selected',
  OWNER_USER: 'owner-user',
  OWNER_MACHINE: 'owner-machine',
}

export const SPOT_COLORS_BY_STATUS = {
  [SPOT_STATUSES.DEFAULT]: '#C3C3C3',
  [SPOT_STATUSES.PRE_SELECTED]: '#FFD192',
  [SPOT_STATUSES.OWNER_USER]: '#FF9F1C',
  [SPOT_STATUSES.OWNER_MACHINE]: '#E71D36',
}
export const SPOT_BORDER_COLORS_BY_STATUS = {
  [SPOT_STATUSES.DEFAULT]: SPOT_COLORS_BY_STATUS[SPOT_STATUSES.DEFAULT],
  [SPOT_STATUSES.PRE_SELECTED]:
    SPOT_COLORS_BY_STATUS[SPOT_STATUSES.PRE_SELECTED],
  [SPOT_STATUSES.OWNER_USER]: SPOT_COLORS_BY_STATUS[SPOT_STATUSES.OWNER_USER],
  [SPOT_STATUSES.OWNER_MACHINE]:
    SPOT_COLORS_BY_STATUS[SPOT_STATUSES.OWNER_MACHINE],
}
