export const PLAYERS_ID = {
  USER: "user",
  MACHINE: "machine",
};

export const BOARD_SETTINGS = {
  COLUMNS: 7,
  SPOT_MARGIN_X: 3.5,
  SPOT_MARGIN_Y: 3,
  SPOT_RADIUS: 87 / 2,
  SPOT_BORDER_WIDTH: 2,
  SPOTS_PER_COLUMN: 6,
  CANVAS_WIDTH: 659,
  CANVAS_HEIGHT: 564,
};

export const SPOT_STATUSES = {
  DEFAULT: "default",
};

export const SPOT_COLORS_BY_STATUS = {
  [SPOT_STATUSES.DEFAULT]: "#C3C3C3",
};
export const SPOT_BORDER_COLORS_BY_STATUS = {
  [SPOT_STATUSES.DEFAULT]: SPOT_COLORS_BY_STATUS[SPOT_STATUSES.DEFAULT],
};
